<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductAttributes;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var ProductAttributes $attributesViewModel */
$attributesViewModel = $viewModels->require(ProductAttributes::class);
/** @var Product $product */
$product = $productViewModel->getProduct();

?>
<div class="w-full mb-0 order-3 px-3 sm:px-0 md:px-0">

    <div class="flex flex-col sm:flex-row justify-between mt-5 md:mt-0">
        <?= $block->getChildHtml("product.info.stockstatus") ?>
        <?= $block->getChildHtml("alert.urls") ?>
    </div>

    <div id="product-details" class="mt-1 mb-4 text-primary">
        <?php foreach ($block->getAttributes() as $attributeConfig) {
            $attribute = $attributesViewModel->getAttributeFromLayoutConfig($attributeConfig); ?>
            <?php if ($value = $attribute['value'] ?? null ) { ?>
                <?php if ($attribute['label'] === "SKU") { ?>
                    <div class=" <?=/* @noEscape */ $attribute['value'] ?: "" ?>">
                        <span class="font-bold">
                            <?= $escaper->escapeHtml($attribute['label']) ?>:
                        </span>
                        <span class="ml-1">
                            <?= $escaper->escapeHtml($value) ?>
                        </span>
                    </div>
                <?php } ?>
            <?php } ?>
        <?php } ?>
    </div>

    <div class="my-6 flex">
        <?= $block->getChildHtml('product.info.review') ?>
    </div>

    <?= $block->getChildHtml('product.info.form') ?>

    <div class="flex flex-col md:flex-col md:gap-4">

        <div role="group" aria-label="<?= $escaper->escapeHtmlAttr('Price') ?>">
            <?= $block->getChildHtml("product.info.price") ?>
        </div>

        <div class="flex gap-5 md:gap-6 flex-col md:flex-row md:flex-row mt-4 sm:mt-0">
            <?php if ($product->isSaleable()): ?>
                <?= $block->getChildHtml("product.info.quantity") ?>
                <?= $block->getChildHtml("product.info.addtocart") ?>
            <?php endif; ?>
        </div>

    </div>

    <?php if ($product->isSaleable()): ?>
        <div class="flex">
            <?= $block->getChildHtml('addtocart.shortcut.buttons') ?>
        </div>
    <?php endif; ?>

    <div class="flex my-6">
        <?= $block->getChildHtml('product.info.addtowishlist'); ?>
        <?= $block->getChildHtml('product.info.addtocompare'); ?>
        <?= $block->getChildHtml('product.info.emailtofriend'); ?>
        <?= $block->getChildHtml('product.info.additional.actions'); ?>
    </div>

    <?= $block->getChildHtml("product.info.additional") ?>

    <?php if ($shortDescription = $productViewModel->getShortDescription()) { ?>
        <div class="mb-4 leading-relaxed product-description prose"><?= /* @noEscape */ $shortDescription ?></div>
    <?php } ?>
</div>
