<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ReCaptcha;
use Magento\Framework\Escaper;
use Magento\Newsletter\Block\Subscribe;

/** @var Subscribe $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var ReCaptcha $recaptcha */
/** @var HeroiconsOutline $heroicons */

$heroicons = $viewModels->require(HeroiconsOutline::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that might break the dependency
// on the Magento_ReCaptchaNewsletter module
$recaptcha = $block->getData('viewModelRecaptcha');
?>
<div class="p-5 sm:pb-5 sm:pt-0 bg-secondary px-3 order-1 md:px-0 sm:mt-12 md:max-w-[617px]">
    <form
        class="form subscribe"
        action="<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>"
        method="post"
        x-data="initNewsletterForm()"
        @submit.prevent="submitForm()"
        id="newsletter-validate-detail"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Subscribe to Newsletter')) ?>"
    >
        <h2
            class="font-bold text-xs uppercase text-white m-0 mb-5 sm:mb-2 leading-5 font-body text-center sm:text-sm"
            id="footer-newsletter-heading"
        >
            <?= $escaper->escapeHtml(__('Newsletter')) ?>
        </h2>
        <p class="text-xs text-white leading-5 text-center sm:text-sm">
            <?= $escaper->escapeHtml(__('Sign up for our newsletter and be the first to find out about new products, discounts and more')) ?>
        </p>
        <div class="sm:flex sm:items-center sm:justify-center">
            <label for="newsletter-subscribe" class="sr-only">
                <?= $escaper->escapeHtml(__('Email Address')) ?>
            </label>
            <input
                name="email"
                type="email"
                required
                id="newsletter-subscribe"
                class="form-input inline-flex w-full my-5 sm:my-7 sm:mr-3 sm:w-[360px]"
                placeholder="<?= $escaper->escapeHtmlAttr(__('Enter your email address')) ?>"
                aria-describedby="footer-newsletter-heading"
            >
            <?= $block->getBlockHtml('formkey') ?>
            <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
            <button class="inline-flex w-full btn btn-primary btn-size-lg sm:w-[130px]">
                <?= $escaper->escapeHtml(__('Subscribe')) ?>
            </button>
        </div>
        <div>
            <template x-if="displayErrorMessage">
                <p class="flex items-center text-red">
                    <span class="inline-block w-8 h-8 mr-3">
                        <?= $heroicons->exclamationCircleHtml(); ?>
                    </span>
                    <template x-for="errorMessage in errorMessages">
                        <span x-html="errorMessage"></span>
                    </template>
                </p>
            </template>
        </div>
    </form>
    <div class="w-full">
        <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
    </div>
    <script>
        function initNewsletterForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                displayErrorMessage: false,
                errorMessages: [],
                setErrorMessages(messages) {
                    this.errorMessages = [messages]
                    this.displayErrorMessage = this.errorMessages.length
                },
                submitForm() {
                    // Do not rename $form, the variable is expected to be declared in the recaptcha output
                    const $form = document.querySelector('#newsletter-validate-detail');
                    <?= $recaptcha ? $recaptcha->getValidationJsHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>

                    if (this.errors === 0) {
                        $form.submit();
                    }
                }
            }
        }
    </script>
</div>
