<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

$uniqueId = '_' . uniqid();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());
?>
<div x-data="initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?>()"
     class="relative z-20 hidden navigation bg-secondary lg:flex"
>
    <!-- desktop -->
    <div x-ref="nav-desktop"
         @load.window="setActiveMenu($root)"
         class="mx-auto hidden w-full lg:block lg:min-h-0"
    >
        <nav
            class="min-h-0 w-auto transform duration-150 ease-in-out transition-display"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Main menu')) ?>"
        >
            <ul class="container mx-auto flex items-center">
                <?php foreach ($menuItems as $index => $menuItem): ?>
                    <li class="level-0 before:content-[''] mb-0 block hover:text-white visited:text-white"
                        @mouseenter="hoverPanelActiveId = '<?= /* @noEscape */ (string) $index ?>'"
                        @mouseleave="hoverPanelActiveId = 0"
                        @keyup.escape="hoverPanelActiveId = 0"
                        style="text-shadow: 0px 2px 4px rgba(0, 0, 0, 0.60);"
                    >
                        <span class="mr-6 flex items-center py-4">
                            <a class="mr-2 w-full text-sm font-normal uppercase leading-5 tracking-widest text-white font-heading level- hover:underline"
                               href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                               title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                               @focus="hoverPanelActiveId = 0"
                            >
                                <?= $escaper->escapeHtml($menuItem['name']) ?>
                            </a>
                            <?php if (!empty($menuItem['childData'])): ?>
                                <button
                                    type="button"
                                    data-sr-button-id="<?= $escaper->escapeHtmlAttr($index) ?>"
                                    :aria-expanded="hoverPanelActiveId === '<?= /* @noEscape */ (string) $index ?>' ? 'true' : 'false'"
                                    @click="openMenuOnClick('<?= /* @noEscape */ (string) $index ?>')"
                                >
                                    <span aria-hidden="true"
                                          style="filter: drop-shadow(0 2px 2px black);"
                                    >
                                        <svg width="9" height="6" viewBox="0 0 9 6" fill="#4E4E4E" class="fill-white transition-transform duration-300" :class="hoverPanelActiveId === '<?= /* @noEscape */ (string) $index ?>' ? 'rotate-180' : ''" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M0.242039 1.66243L3.91704 5.16243C4.15652 5.39051 4.54424 5.39051 4.78311 5.16243L8.45811 1.66243C8.6976 1.43435 8.6976 1.0651 8.45811 0.837597C8.21862 0.610097 7.83091 0.609514 7.59204 0.837597L4.35007 3.92518L1.10811 0.837597C0.868626 0.609514 0.480913 0.609514 0.242039 0.837597C0.00316362 1.06568 0.00255111 1.43493 0.242039 1.66243Z"/>
                                        </svg>
                                    </span>

                                    <span class="sr-only">
                                        <?= $escaper->escapeHtml(__('Show submenu for %1 category', $menuItem['name'])) ?>
                                    </span>
                                </button>
                            <?php endif; ?>
                        </span>
                        <?php if (!empty($menuItem['childData'])): ?>
                            <div class="absolute left-0 z-10 block flex w-screen origin-top items-center justify-center bg-white transition-transform duration-500 top-[52px]"
                                 :class="hoverPanelActiveId === '<?= /* @noEscape */ (string) $index ?>' ? 'scale-y-100' : 'scale-y-0'"
                            >
                                <ul class="mt-4 ml-0 flex gap-8 pb-3">
                                    <?php foreach ($menuItem['childData'] as $subMenuItem): ?>
                                        <li style="text-shadow: none;"
                                            class="before:content-[''] flex flex-col items-start"
                                        >
                                            <a href="<?= $escaper->escapeUrl($subMenuItem['url']) ?>"
                                               title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>"
                                               class="block w-fullwhitespace-nowrap hover:underline"
                                               @keyup.escape="$nextTick(() => document.querySelector('[data-sr-button-id=<?= $escaper->escapeJs($index) ?>]').focus())"
                                            >
                                                <span class="text-sm font-bold uppercase leading-5 tracking-widest text-black">
                                                    <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                                </span>
                                            </a>

                                            <?php if (!empty($subMenuItem['childData'])): ?>
                                                <ul class="mt-4 ml-0">
                                                    <?php foreach ($subMenuItem['childData'] as $thirdSubMenuItem): ?>
                                                        <li class="before:content-[''] block max-w-[220px]">
                                                            <a
                                                                href="<?= $escaper->escapeUrl($thirdSubMenuItem['url']) ?>"
                                                                title="<?= $escaper->escapeHtmlAttr($thirdSubMenuItem['name']) ?>"
                                                                class="text-sm uppercase leading-5 tracking-widest text-black visited:text-black hover:underline"
                                                            >
                                                                <?= $escaper->escapeHtml($thirdSubMenuItem['name']) ?>
                                                            </a>
                                                        </li>
                                                    <?php endforeach; ?>
                                                </ul>
                                            <?php endif; ?>
                                        </li>
                                    <?php endforeach; ?>
                                    <li class="before:content-[''] flex flex-col items-start"
                                        style="text-shadow: none;"
                                    >
                                        <a href="#" class="text-sm font-bold uppercase leading-5 tracking-widest text-black hover:underline visited:text-black">Contact Us</a>
                                        <ul class="mt-4 ml-0 text-text">
                                            <li class="before:content-[''] flex items-center gap-0 mb-0">
                                                <?= $hyvaicons->renderHtml('location', 'w-3 mr-2'); ?>
                                                Trg slobode 6
                                            </li>
                                            <li class="before:content-[''] flex items-center gap-0 mb-0">
                                                <?= $hyvaicons->renderHtml('phone', 'w-3 mr-2'); ?>
                                                +385958811630
                                            </li>
                                            <li class="before:content-[''] flex items-center gap-0">
                                                <?= $hyvaicons->renderHtml('mail', 'w-3 mr-2'); ?>
                                                filip.svetlicic@gmail.com
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
                <li class="block before:content-[''] mb-0 hover:text-white"
                    style="text-shadow: 0px 2px 4px rgba(0, 0, 0, 0.60);"
                >
                    <a href="<?= $escaper->escapeUrl($block->getUrl('contact')) ?>" class="text-sm font-normal uppercase leading-5 tracking-widest text-white font-heading visited:text-white hover:underline">
                        CONTACT us
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>

<script>
    'use strict';

    const initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            hoverPanelActiveId: null,
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    item.classList.add('underline');
                    item.closest('div.level-0') &&
                    item.closest('div.level-0').querySelector('a.level-0').classList.add('underline');
                });
            },
            openMenuOnClick(menuNode) {
                if (menuNode === this.hoverPanelActiveId) {
                    this.hoverPanelActiveId = 0;
                } else {
                    this.hoverPanelActiveId = menuNode
                }
            }
        }
    }
</script>
