<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

$uniqueId = '_' . uniqid();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

?>
<nav
    x-data="initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?>()"
    @load.window="setActiveMenu($root)"
    @keydown.window.escape="closeMenu()"
    class="z-20 order-2 mx-5 h-4 w-4 navigation sm:order-1 lg:order-2 lg:hidden"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation')) ?>"
    role="navigation"
>
    <!-- mobile -->
    <button
        x-ref="mobileMenuTrigger"
        @click="openMenu()"
        :class="{'overflow-x-hidden overflow-y-auto fixed top-0 left-0 w-full' : open}"
        type="button"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Open menu')) ?>"
        aria-haspopup="menu"
        :aria-expanded="open"
        :hidden="open"
    >
        <span x-bind:class="{ 'hidden': open, 'block': !open }" aria-hidden="true">
            <?= $hyvaicons->renderHtml('hamburger-menu', 'w-4 h-4', 16, 16); ?>
        </span>
    </button>
    <div
        x-ref="mobileMenuNavLinks"
        class="
            fixed top-0 right-0 w-full h-full p-1 hidden
            flex-col border-t border-container bg-white
            overflow-y-auto overflow-x-hidden"
        :class="{ 'flex': open, 'hidden': !open }"
        :aria-hidden="open ? 'false' : 'true'"
        role="dialog"
        aria-modal="true"
    >
        <p class="absolute top-16 left-3 text-sm uppercase text-primary">Menu</p>
        <ul
            class="mt-28 ml-0 flex flex-col"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation links')) ?>"
        >
            <?php foreach ($menuItems as $index => $menuItem): ?>
                <li
                    data-child-id="<?= $escaper->escapeHtmLAttr($index) ?>-main"
                    class="block level-0 before:content-[''] mx-2"
                    x-data="{
                        open: false,
                        toggle() { this.open = ! this.open }
                    }"
                >
                    <div
                        class="flex transform items-center transition-transform duration-150 ease-in-out"
                        :class="{
                            '-translate-x-full' : mobilePanelActiveId,
                            'translate-x-0' : !mobilePanelActiveId
                        }"
                    >
                        <a
                            class="flex items-center w-full border-b cursor-pointer
                                bg-container-lighter border-container level-0 text-xs font-bold uppercase leading-6 tracking-widest text-text py-2"
                            :class="open ? 'border-none' : ''"
                            href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                            title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                        >
                            <?= $escaper->escapeHtml($menuItem['name']) ?>
                        </a>
                        <?php if (!empty($menuItem['childData'])): ?>
                            <button
                                @click="toggle()"
                                :class="open ? 'rotate-180' : ''"
                                class="absolute right-0 flex items-center justify-center cursor-pointer
                                bg-container-lighter border-container"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Open %1 subcategories', $menuItem['name'])) ?>"
                                aria-haspopup="true"
                                :aria-expanded="mobilePanelActiveId === '<?= /* @noEscape */ (string) $index ?>'"
                            >
                                <?= $hyvaicons->renderHtml('chevron-down', 'w-2'); ?>
                            </button>
                        <?php endif; ?>
                    </div>
                    <?php if (!empty($menuItem['childData'])): ?>
                        <div
                            data-child-id="<?= $escaper->escapeHtmLAttr($index) ?>"
                            x-show="open"
                        >
                            <ul
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Subcategories')) ?>"
                            >
                                <?php foreach ($menuItem['childData'] as $subMenuItem): ?>
                                    <li class="before:content-[''] block"
                                        x-data="{
                                            openSubmenu: false,

                                            toggleSubmenu() {
                                                this.openSubmenu = !this.openSubmenu;
                                            }
                                        }"
                                    >
                                        <div class="my-2 flex items-center gap-2 text-xs uppercase leading-6 tracking-widest"
                                        >
                                            <?php if (!empty($subMenuItem['childData'])): ?>
                                                <span @click="toggleSubmenu()" :class="openSubmenu ? 'rotate-45' : '' " class="cursor-pointer">
                                                    <?= $hyvaicons->renderHtml('close-menu', 'w-[0.75rem] h-[0.75rem] rotate-45'); ?>
                                                </span>
                                            <?php else: ?>
                                            <span class="w-3">
                                                &nbsp;
                                                <!-- White space to be align with other links if there is no subcategory -->
                                            </span>

                                            <?php endif; ?>

                                            <a href="<?= $escaper->escapeUrl($subMenuItem['url']) ?>"
                                               title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>">
                                                <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                            </a>
                                        </div>
                                        <?php if (!empty($subMenuItem['childData'])): ?>
                                            <ul class="ml-8"
                                                x-show="openSubmenu"
                                            >
                                                <?php foreach ($subMenuItem['childData'] as $thirdSubMenuItem): ?>
                                                    <li class="before:content-['']">
                                                        <a
                                                            href="<?= $escaper->escapeUrl($thirdSubMenuItem['url']) ?>"
                                                            title="<?= $escaper->escapeHtmlAttr($thirdSubMenuItem['name']) ?>"
                                                            class="text-xs uppercase leading-6 tracking-widest"
                                                        >
                                                            <?= $escaper->escapeHtml($thirdSubMenuItem['name']) ?>
                                                        </a>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
        <button
            @click="closeMenu()"
            class="absolute top-6 right-3 flex items-center gap-2 text-sm"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Close menu')) ?>"
            type="button"
        >
            Close
            <span x-bind:class="{ 'hidden': !open, 'block': open }" aria-hidden="true">
                <?= $hyvaicons->renderHtml('close-menu', 'w-[0.75rem] h-[0.75rem]'); ?>
            </span>
        </button>
    </div>
</nav>
<script>
    'use strict';

    const initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            mobilePanelActiveId: null,
            open: false,
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    item.classList.add('underline');
                    item.closest('li.level-0') &&
                    item.closest('li.level-0').querySelector('a.level-0').classList.add('underline');
                });
            },
            openMenu() {
                this.open = true
                this.$nextTick(() => hyva.trapFocus(this.$refs['mobileMenuNavLinks']));
                // Prevent from body scrolling while mobile menu opened
                document.body.style.position = 'fixed';
            },
            closeMenu() {
                document.body.style.position = '';

                if (this.open) {
                    this.$nextTick(() => this.$refs['mobileMenuTrigger'].focus() || hyva.releaseFocus());
                }

                this.open = false
                this.mobilePanelActiveId = null
            },
        }
    }
</script>
