<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$item = $block->getData('item');

?>
<div class="block h-[22.313rem] w-full relative md:h-[39rem]">
    <img class="absolute h-full w-full object-cover" src="<?= $escaper->escapeHtmlAttr($item['image_url']) ?>"
         alt="<?= $escaper->escapeHtmlAttr($item['title']) ?>"
         width="<?= $escaper->escapeHtmlAttr($item['image_width'] ?? '1600') ?>"
         height="<?= $escaper->escapeHtmlAttr($item['image_height'] ?? '624') ?>"
         loading="lazy"
    />
    <div class="absolute top-[9.25rem] md:top-[13.5rem] text-center w-full bottom-0 bg-gradient-to-t from-gray-800/50 to-transparent">
        <h2 class="text-white leading-10 text-2xl md:text-3xl mb-10 md:mb-20 mt-0"
            style="text-shadow: 0px 2px 4px rgba(0, 0, 0, 0.60);"
        >
            <?= $escaper->escapeHtml($item['title']) ?>
        </h2>
        <a href="<?= $escaper->escapeUrl($item['url'])?>"
           :id="$id('slide-desc')"
           class="btn btn-size-sm btn-primary text-white visited:text-white"
        >
            <?= $escaper->escapeHtml($item['text_link']) ?>
        </a>
    </div>
</div>
