<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\AbstractBlock;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var AbstractBlock $sectionBlock */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

?>
<div>
    <h2 class="text-secondary font-body font-bold text-sm my-0 uppercase leading-6 md:text-base flex items-center justify-between py-2"
        @click="toggle()"
    >
        <?= $sectionBlock->getTitle() ? $escaper->escapeHtml($sectionBlock->getTitle()) : '&nbsp;' ?>
        <span :class="open ? 'rotate-180' : ''">
            <?= $hyvaicons->renderHtml('chevron-down', 'w-2'); ?>
        </span>
    </h2>
</div>
