<h2 class="leading-6 mb-5">ATOMS</h2>
<h3 class="text-tertiary-25 mb-4">Main Colors</h3>

<div class="grid grid-cols-4 place-items-start">
    <div class="flex flex-col gap-6">
        <div class="flex items-center gap-3">
            <div class="bg-primary rounded-full w-16 h-16"></div>
            <p class="text-base">--primary__color</p>
        </div>
        <div class="flex items-center gap-3">
            <div class="bg-secondary rounded-full w-16 h-16"></div>
            <p class="text-base">--secondary__color</p>
        </div>
    </div>

    <div class="flex flex-col gap-2">
        <div class="flex items-center gap-2">
            <div class="rounded-full w-6 h-6 bg-tertiary-90"></div>
            <p>--tertiary-90</p>
        </div>
        <div class="flex items-center gap-2">
            <div class="rounded-full w-6 h-6 bg-tertiary-60"></div>
            <p>--tertiary-60</p>
        </div>
        <div class="flex items-center gap-2">
            <div class="rounded-full w-6 h-6 bg-tertiary-25"></div>
            <p>--tertiary-25</p>
        </div>
        <div class="flex items-center gap-2">
            <div class="rounded-full w-6 h-6 bg-tertiary-10"></div>
            <p>--tertiary-10</p>
        </div>
        <div class="flex items-center gap-2">
            <div class="rounded-full w-6 h-6 bg-tertiary-5"></div>
            <p>--tertiary-5</p>
        </div>
    </div>

    <div class="flex items-center gap-2">
        <div class="rounded-full w-6 h-6 bg-secondary-90"></div>
        <p>--secondary-90</p>
    </div>

    <div class="flex flex-col gap-6">
        <div class="flex items-center gap-2">
            <div class="rounded-full w-6 h-6 bg-white"></div>
            <p>--color-white</p>
        </div>
        <div class="flex items-center gap-2">
            <div class="rounded-full w-6 h-6 bg-success"></div>
            <p>--success__color</p>
        </div>
        <div class="flex items-center gap-2">
            <div class="rounded-full w-6 h-6 bg-error"></div>
            <p>--error__color</p>
        </div>
        <div class="flex items-center gap-2">
            <div class="rounded-full w-6 h-6 bg-warning"></div>
            <p>--warning__color</p>
        </div>
    </div>
</div>






