<h2 class="mt-20 mb-5 leading-6">ATOMS</h2>

<div class="grid grid-cols-4">
    <div class="flex flex-col gap-2">
        <h3 class="text-tertiary-25">Input Field Colors</h3>
        <div class="flex items-center gap-2">
            <div class="h-6 w-6 rounded-full bg-white"></div>
            <p>--input-background-color-default</p>
        </div>
        <div class="flex items-center gap-2">
            <div class="h-6 w-6 rounded-full bg-tertiary-5"></div>
            <p>--input-background-color-disabled</p>
        </div>
    </div>
    <div class="flex flex-col gap-2">
        <h3 class="text-tertiary-25">Input Field Border Colors</h3>
        <div class="flex items-center gap-2">
            <div class="h-6 w-6 rounded-full bg-tertiary-25"></div>
            <p>--input-border-color-default</p>
        </div>
        <div class="flex items-center gap-2">
            <div class="h-6 w-6 rounded-full bg-form-border-focus"></div>
            <p>--input-border-color-focus</p>
        </div>
        <div class="flex items-center gap-2">
            <div class="h-6 w-6 rounded-full bg-form-border-err"></div>
            <p>--input-border-color-error</p>
        </div>
    </div>
    <div class="flex flex-col">
        <h3 class="text-tertiary-25">Forms Text</h3>
        <p class="text-sm leading-6">form/label/mobile</p>
        <p class="text-base leading-6">form/label/desktop</p>
        <br>
        <p class="text-sm leading-7 text-tertiary-60">form/placeholder/mobile</p>
        <p class="text-base leading-7 text-tertiary-60">form/placeholder/desktop</p>
    </div>
    <div class="flex flex-col gap-2">
        <h3 class="text-tertiary-25">Form Text Colors</h3>
        <div class="flex items-center gap-2">
            <div class="h-6 w-6 rounded-full bg-form-label"></div>
            <p>--form-label-color</p>
        </div>
        <div class="flex items-center gap-2">
            <div class="h-6 w-6 rounded-full bg-tertiary-60"></div>
            <p>--form-placeholder-color</p>
        </div>
        <div class="flex items-center gap-2">
            <div class="h-6 w-6 rounded-full bg-tertiary-90"></div>
            <p>--form-help-txt-color</p>
        </div>
    </div>
</div>

<h3 class="text-tertiary-25">Radio and Ckeckbox icons</h3>
<div class="mb-10 grid w-52 grid-cols-2">
    <div>
        <input type="radio" id="radioBtn1" name="radioGroup" checked>
        <label for="radioBtn1">Radio</label>
    </div>
    <div>
        <input type="radio" id="radioBtn2" name="radioGroup">
        <label for="radioBtn2">Radio</label>
    </div>
    <div>
        <input type="checkbox" id="checkbox1" checked>
        <label for="checkbox1" onclick="">Checkbox</label>
    </div>
    <div>
        <input type="checkbox" id="checkbox2">
        <label for="checkbox2" onclick="">Checkbox</label>
    </div>
</div>

<h3 class="text-tertiary-25">Form</h3>
<form class="flex flex-col items-start gap-2" action="#">
    <label for="input1">input label</label>
    <input placeholder="Placeholder" class="w-[320px]" type="text" id="input1">
    <input type="radio" id="radio-btn-1" name="radioGroup">
    <label for="radio-btn-1">0,00&euro;</label>
    <input type="checkbox" id="chk-box-1">
    <label for="chk-box-1">0,00&euro;</label>

    <label for="cars">forms/select</label>
    <select name="cars" id="cars">
        <option value="volvo">Bestseller</option>
    </select>
</form>

<h3 class="text-tertiary-25">MOLECULES</h3>
<form class="flex flex-col items-start gap-5" action="#">
    <div>
        <label for="select-1">Label *</label>
        <select name="select-1" id="select-1">
            <option value="volvo">Bestseller</option>
        </select>
    </div>
    <div>
        <label for="input-1">Label *</label>
        <input type="text" id="input-1" placeholder="Placeholder">
    </div>
    <div>
        <label for="input-1">Label *</label>
        <input type="email" id="input-1" placeholder="Placeholder">
        <p class="input-err">Error text example</p>
    </div>
    <div>
        <label for="input-1">Input Disabled</label>
        <input type="text" id="input-1" placeholder="Placeholder" disabled>
    </div>
</form>


