<h2 class="mt-20 mb-5 leading-6">ATOMS</h2>

<h3 class="text-tertiary-25">Table</h3>

<table>
    <tr>
        <th>Style:</th>
        <td>Insulated, Heavy Duty, Soft Shell, ¼ zip</td>
    </tr>
    <tr>
        <th>Material:</th>
        <td>Fleece, Polyester, Wool</td>
    </tr>
    <tr>
        <th>Pattern:</th>
        <td>Solid</td>
    </tr>
    <tr>
        <th>Climate:</th>
        <td>All-Weather, Cool, Indoor, Spring</td>
    </tr>
</table>
