<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\ViewModel\Navigation;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

$menuItems = $viewModelNavigation->getNavigation(1);
?>
<div class="order-3 w-full px-3">
    <div class="">
        <div x-data="{
                open: false,
                toggle() {
                    this.open = !this.open;
                }
            }
        ">
            <h2 class="my-2 flex items-center justify-between text-xs font-bold uppercase leading-6 tracking-wider text-white font-body"
                @click="toggle()"
            >
                Contact us
                <span :class="open ? 'rotate-180' : ''">
                    <?= $hyvaicons->renderHtml('chevron-down', 'w-2 fill-white'); ?>
                </span>
            </h2>
            <ul class="my-3 ml-4 ml-0 text-white"
                x-show="open"
            >
                <li class="before:content-[''] flex items-center gap-0 mb-0">
                    <?= $hyvaicons->renderHtml('location', 'w-3 mr-2 fill-white'); ?>
                    Trg slobode 6
                </li>
                <li class="before:content-[''] flex items-center gap-0 mb-0">
                    <?= $hyvaicons->renderHtml('phone', 'w-3 mr-2 fill-white'); ?>
                    +385958811630
                </li>
                <li class="before:content-[''] flex items-center gap-0 mb-0">
                    <?= $hyvaicons->renderHtml('mail', 'w-3 mr-2 fill-white'); ?>
                    filip.svetlicic@gmail.com
                </li>
            </ul>
        </div>
        <div x-data="{
                open: false,
                toggle() {
                    this.open = !this.open;
                }
            }
        ">
            <h2 class="my-2 flex items-center justify-between text-xs font-bold uppercase leading-6 tracking-wider text-white font-body"
                @click="toggle()"
            >
                Categories
                <span :class="open ? 'rotate-180' : ''">
                    <?= $hyvaicons->renderHtml('chevron-down', 'w-2 fill-white'); ?>
                </span>
            </h2>
            <ul class="my-3 ml-4 ml-0"
                x-show="open"
            >
                <?php foreach ($menuItems as $index => $menuItem): ?>
                <li class="mb-0">
                    <a
                        href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                        title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                        class="leading-6 text-white visited:text-white"
                    >
                        <?= $escaper->escapeHtml($menuItem['name']) ?>
                    </a>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
