<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\ViewModel\Navigation;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

$menuItems = $viewModelNavigation->getNavigation(1);
?>
<div class="order-3 w-full px-3 py-2">
    <div class="sm:flex sm:items-start sm:justify-center">
        <div x-data="{
                open: true,
                alwaysShow: window.innerWidth > 640,
                toggle() {
                    if(this.alwaysShow) {
                        this.open = true;
                    } else {
                        this.open = !this.open;
                    }
                }
            }
        "
             x-init="toggle()"
             @resize.window="alwaysShow = window.innerWidth > 640; open = alwaysShow ? true : false"
             class="sm:order-2 sm:w-[12.75rem]"
        >
            <h2 class="mb-4 sm:mb-6 mt-0 flex items-center justify-between text-xs font-bold uppercase leading-6 tracking-wider text-white font-body sm:mt-4 sm:text-sm sm:leading-6"
                @click="toggle()"
            >
                Contact us
                <span  class="sm:hidden"
                       :class="open ? 'rotate-180' : ''"
                >
                    <?= $hyvaicons->renderHtml('chevron-down', 'w-2 fill-white'); ?>
                </span>
            </h2>
            <ul class="my-3 ml-4 sm:ml-0 ml-0 text-white"
                x-show="open"
            >
                <li class="before:content-[''] flex items-center gap-0 mb-0">
                    <?= $hyvaicons->renderHtml('location', 'w-3 mr-2 fill-white'); ?>
                    Trg slobode 6
                </li>
                <li class="before:content-[''] flex items-center gap-0 mb-0">
                    <?= $hyvaicons->renderHtml('phone', 'w-3 mr-2 fill-white'); ?>
                    +385958811630
                </li>
                <li class="before:content-[''] flex items-center gap-0 mb-0">
                    <?= $hyvaicons->renderHtml('mail', 'w-3 mr-2 fill-white'); ?>
                    filip.svetlicic@gmail.com
                </li>
            </ul>
        </div>
        <div x-data="{
                open: true,
                alwaysShow: window.innerWidth > 640,
                toggle() {
                    if(this.alwaysShow) {
                        this.open = true;
                    } else {
                        this.open = !this.open;
                    }
                }
            }
        "
             x-init="toggle()"
             class="sm:w-[12.75rem] sm:mr-[9.625rem]"
             @resize.window="alwaysShow = window.innerWidth > 640; open = alwaysShow ? true : false"
        >
            <h2 class="mt-0 mb-0 flex items-center justify-between text-xs font-bold uppercase leading-6 tracking-wider text-white font-body sm:mt-4 sm:mb-6 sm:text-sm sm:leading-6"
                @click="toggle()"
            >
                Categories
                <span class="sm:hidden"
                      :class="open ? 'rotate-180' : ''"
                >
                    <?= $hyvaicons->renderHtml('chevron-down', 'w-2 fill-white'); ?>
                </span>
            </h2>
            <ul class="my-3 ml-4 ml-0 sm:ml-0"
                x-show="open"
            >
                <?php foreach ($menuItems as $index => $menuItem): ?>
                <li class="mb-0">
                    <a
                        href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                        title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                        class="leading-6 text-white visited:text-white hover:underline hover:text-white"
                    >
                        <?= $escaper->escapeHtml($menuItem['name']) ?>
                    </a>
                </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
