<?php

declare(strict_types=1);

use Magento\Theme\Block\Html\Breadcrumbs;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\Model\ViewModelRegistry;

/** @var Escaper $escaper */
/** @var Breadcrumbs $block */
/** @var array[] $crumbs */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
?>
<?php if ($crumbs && is_array($crumbs)): ?>
<nav class="breadcrumbs" aria-label="Breadcrumb">
    <div class="sm:container sm:mx-auto">
        <ol class="items list-reset flex flex-wrap text-sm mx-3 sm:mx-0 mt-5 md:mt-6">
            <?php foreach ($crumbs as $crumbName => $crumbInfo): ?>
                <?php if ($crumbName === 'product') continue; ?>
                <li class="item flex ml-0 mb-0 items-center last:font-bold last:text-secondary-25 group <?= $escaper->escapeHtmlAttr($crumbName) ?>">
                <?php if (!$crumbInfo['first']): ?>
                    <span aria-hidden="true" class="px-2">
                        <?= $hyvaicons->renderHtml('chevron-right', 'w-1'); ?>
                    </span>
                <?php endif; ?>
                <?php if ($crumbInfo['link']): ?>
                    <a href="<?= $escaper->escapeUrl($crumbInfo['link']) ?>"
                       class="no-underline leading-5 text-xs text-secondary visited:text-secondary group-[:nth-last-child(1)]:text-text"
                       title="<?= $escaper->escapeHtmlAttr($crumbInfo['title']) ?>"
                    ><?= $escaper->escapeHtml($crumbInfo['label']) ?></a>
                <?php elseif (!$crumbInfo['last']): ?>
                    <?= $escaper->escapeHtml($crumbInfo['label']) ?>
                <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
</nav>
<?php endif; ?>
