<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<div class="bg-secondary">
    <div class="container mx-auto sm:flex sm:items-center sm:justify-center">
        <?= $block->getBlockHtml('form.subscribe') ?>
    </div>
</div>
<div class="bg-primary">
    <?= $block->getChildHtml('footer-static-links') ?>
</div>
<div class="bg-black flex items-center justify-center">
    <p class="leading-6 py-2 sm:py-3 text-white text-xs">
        <?= $block->getChildHtml('copyright') ?>
    </p>
</div>

