<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\Navigation;

// phpcs:disable Generic.Files.LineLength

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

$menuItems = $viewModelNavigation->getNavigation(1);
?>
<section class="container mx-auto mt-4 sm:my-8">
    <h2 class="text-center text-black text-xl leading-10 mb-5 mt-0 md:mb-6 md:text-2xl md:leading-[3rem]">
        <?= $escaper->escapeHtml(__('Featured Categories')) ?>
    </h2>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5 sm:gap-7 justify-items-center">
        <?php foreach ($menuItems as $index => $menuItem): ?>

        <div class="relative before:content-[''] before:bg-gradient-to-t before:from-[#00000068] before:to-transparent before:absolute before:top-0 before:w-full before:left-0 before:h-full cursor-pointer"
             x-data=""
             @click="window.location.href = '<?= $menuItem['url']; ?>'"
        >
            <img src="<?= $menuItem['image']; ?>"
                 alt="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                 class="w-[21rem] h-[10.5] sm:h-[11.875rem] object-cover "
                 width="336"
                 height="168"
            >
            <h3 class="absolute bottom-4 left-3 z-10 text-white text-base m-0"
                style="text-shadow: 0px 2px 4px rgba(0, 0, 0, 0.60);"
            >
                <?= $escaper->escapeHtml($menuItem['name']) ?>
            </h3>
        </div>

        <?php endforeach; ?>
    </div>
</section>
