<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\View\Element\Template;

/** @var ViewModelRegistry $viewModels */
/** @var Slider $sliderViewModel */
/** @var Template $block */

$sliderViewModel = $viewModels->require(Slider::class);

/**
 * These items are examples. You could query products, categories, etc..
 * Change the slider-item.phtml accordingly to display the correct properties.
 */
$items = [
    [
        'image_url'    => $block->getViewFileUrl('images/hero-slider-bg.jpeg'),
        'image_width'  => 1600,
        'image_height' => 624,
        'title'   => 'THE FLYING DISC STORE',
        'text_link'   => 'BUY THE DISC',
        'url'          => '/',
    ],
    [
        'image_url'    => 'https://unsplash.com/photos/HyvE5SiKMUs/download?force=true&auto=format&fit=crop&w=1280&q=80',
        'image_width'  => 1600,
        'image_height' => 624,
        'title'   => 'SUMMER COLLECTION',
        'text_link'   => 'GET YOUR GEAR NOW',
        'url'          => '/',
    ],
    [
        'image_url'    => 'https://unsplash.com/photos/zlPmPfXfr4A/download?force=true&auto=format&fit=crop&w=1280&q=80',
        'image_width'  => 1600,
        'image_height'  => 624,
        'title' => 'WINTER COLLECTION',
        'text_link' => 'SHOW YOUR STYLE',
        'url'          => '/',
    ],
];

?>
<div class="">
    <?=
    $sliderViewModel
        ->getSliderForItems(
            'Magento_Theme::elements/ui-slider/slider-item.phtml',
            $items,
            'Magento_Theme::elements/ui-slider/slider-php.phtml'
        )
        ->setData('test', __('Test'))
        ->toHtml()
    ?>
</div>
