<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$storeConfig = $viewModels->require(StoreConfig::class);
$maxItemsToDisplay = $storeConfig->getStoreConfig('checkout/sidebar/max_items_display_count');

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);
?>
<script>
    function initCartDrawer() {
        return {
            open: false,
            isLoading: false,
            cart: {},
            maxItemsToDisplay: <?= (int) $maxItemsToDisplay ?>,
            itemsCount: 0,
            totalCartAmount: 0,
            getData(data) {
                if (data.cart) {
                    this.cart = data.cart;
                    this.itemsCount = data.cart.items && data.cart.items.length || 0;
                    this.totalCartAmount = this.cart.summary_count;
                    this.setCartItems();
                }
                this.isLoading = false;
            },
            cartItems: [],
            getItemCountTitle() {
                return hyva.strf('<?= $escaper->escapeJs(__('%0 of %1 products in cart displayed')) ?>', this.maxItemsToDisplay, this.totalCartAmount)
            },
            setCartItems() {
                this.cartItems = this.cart.items && this.cart.items.sort((a, b) => b.item_id - a.item_id) || [];

                if (this.maxItemsToDisplay > 0) {
                    this.cartItems = this.cartItems.slice(0, parseInt(this.maxItemsToDisplay, 10));
                }
                console.log(this.cartItems);
            },
            deleteItemFromCart(itemId) {
                this.isLoading = true;

                const formKey = hyva.getFormKey();
                const postUrl = BASE_URL + 'checkout/sidebar/removeItem/';

                fetch(postUrl, {
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    "body": "form_key=" + formKey + "&item_id=" + itemId,
                    "method": "POST",
                    "mode": "cors",
                    "credentials": "include"
                }).then(response => {
                    if (response.redirected) {
                        window.location.href = response.url;
                    } else if (response.ok) {
                        return response.json();
                    } else {
                        window.dispatchMessages && window.dispatchMessages([{
                            type: 'warning',
                            text: '<?= $escaper->escapeJs(__('Could not remove item from quote.')) ?>'
                        }]);
                        this.isLoading = false;
                    }
                }).then(result => {
                    window.dispatchMessages && window.dispatchMessages([{
                        type: result.success ? 'success' : 'error',
                        text: result.success
                            ? '<?= $escaper->escapeJs(__('You removed the item.')) ?>'
                            : result.error_message
                    }], result.success ? 5000 : 0)
                    window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
                });
            },
            toggleCartDrawer(event) {
                if (event.detail && event.detail.isOpen !== undefined) {
                    if (event.detail.isOpen) {
                        this.openCartDrawer()
                    } else {
                        this.open = false
                        this.$refs && this.$refs.cartDialogContent && hyva.releaseFocus(this.$refs.cartDialogContent)
                    }
                } else {
                    <?php
                    /*
                     * The toggle-cart event was previously dispatched without parameter to open the drawer (not toggle).
                     * Keeping this in here for backwards compatibility.
                     */
                    ?>
                    this.openCartDrawer()
                }
            },
            openCartDrawer() {
                this.open = true;
                this.$nextTick(() => {
                    this.$refs && this.$refs.cartDialogContent && hyva.trapFocus(this.$refs.cartDialogContent)
                })
            },
            closeCartDrawer() {
                this.$dispatch('toggle-cart', { isOpen: false })
            }
        }
    }
</script>
<section x-cloak
         x-show="cart"
         id="cart-drawer"
         x-data="initCartDrawer()"
         @private-content-loaded.window="getData($event.detail.data)"
         @toggle-cart.window="toggleCartDrawer($event)"
         @keydown.escape="closeCartDrawer"
>
    <div role="dialog"
         aria-labelledby="cart-drawer-title"
         aria-modal="true"
         :aria-hidden="!open"
         class="fixed inset-y-0 right-0 z-30 flex max-w-full">
        <div class="backdrop"
             x-show="open"
             x-transition:enter="ease-in-out duration-500"
             x-transition:enter-start="opacity-0"
             x-transition:enter-end="opacity-100"
             x-transition:leave="ease-in-out duration-500"
             x-transition:leave-start="opacity-100"
             x-transition:leave-end="opacity-0"
             role="button"
             @click="closeCartDrawer"
             aria-label="<?= $escaper->escapeHtmlAttr(__('Close minicart')) ?>"></div>
        <div class="relative w-screen max-w-[695px] shadow-2xl"
             x-show="open"
             x-transition:enter="transform transition ease-in-out duration-500 sm:duration-700"
             x-transition:enter-start="translate-x-full"
             x-transition:enter-end="translate-x-0"
             x-transition:leave="transform transition ease-in-out duration-500 sm:duration-700"
             x-transition:leave-start="translate-x-0"
             x-transition:leave-end="translate-x-full"
             x-ref="cartDialogContent"
             role="region"
             :tabindex="open ? 0 : -1"
             aria-label="<?= $escaper->escapeHtmlAttr(__('My Cart')) ?>"

        >
            <div class="flex flex-col h-full max-h-screen bg-white shadow-xl">
                <?= $block->getChildHtml('cart-drawer.top'); ?>

                <template x-if="itemsCount">
                    <div class="ml-3 sm:ml-7 mt-20 mb-6 font-bold text-text text-xs leading-6">
                        <p class="uppercase">
                            <span x-text="itemsCount"></span>
                            <?= __('item in cart') ?>
                        </p>
                        <p class="mt-6">
                            <?= __('Recently added items') ?>
                        </p>
                    </div>
                </template>

                <?= $block->getChildHtml('cart-drawer.items.before'); ?>

                <template x-if="!itemsCount">
                    <p class="ml-3 sm:ml-7 mt-20 font-bold text-text text-xs leading-6">
                        <?= $escaper->escapeHtml(__('You have no items in your shopping cart')) ?>
                    </p>
                </template>

                <template x-if="itemsCount">
                    <div class="grid overflow-y-auto overscroll-y-contain gap-6"
                    >
                        <template x-for="item in cartItems">
                            <div class="flex items-start px-3 sm:px-7">
                                <a :href="item.product_url"
                                    class=""
                                    :aria-label="hyva.strf('<?= $escaper->escapeJs(__('Product "%0"')) ?>', item.product_name)"
                                >
                                    <img
                                        :src="item.product_image.src"
                                        loading="lazy"
                                        alt=""
                                        class="w-[78px] sm:w-[90px]"
                                    />
                                </a>
                                <div class="w-3/4 flex-1 ml-6 sm:ml-7">
                                    <p class="text-sm text-secondary uppercase font-bold leading-6 line-clamp-2">
                                        <span x-html="item.product_name"></span>
                                    </p>
                                    <template x-for="option in item.options">
                                        <div class="mt-3 mb-2 text-xs text-text leading-6">
                                            <span class="font-bold " x-text="option.label + ':'"> </span>
                                            <span class="" x-html="option.value"></span>
                                        </div>
                                    </template>
                                    <p class="text-text text-xs leading-6"><span x-html="item.product_price"></span></p>
                                    <div class="mt-2 flex items-center">
                                        <label for="qty-change-input" class="text-xs font-bold text-text">Qty: </label>
                                        <input id="qty-change-input" x-bind:value="item.qty" type="number" class="ml-1 w-16">
                                    </div>
                                    <div class="pt-5 flex justify-end">
                                        <a :href="item.configure_url"
                                            x-show="item.product_type !== 'grouped'"
                                            class="mr-6"
                                            :aria-label="hyva.strf('<?= $escaper->escapeJs(__('Edit product "%0"')) ?>', item.product_name)"
                                        >
                                            <span aria-hidden="true">
                                                <?= $hyvaicons->renderHtml('edit', 'w-4'); ?>
                                            </span>
                                        </a>
                                        <button type="button"
                                                class=""
                                                @click="deleteItemFromCart(item.item_id)"
                                                :aria-label="hyva.strf('<?= $escaper->escapeJs(__('Remove product "%0" from cart')) ?>', item.product_name)"
                                        >
                                            <span aria-hidden="true">
                                                <?= $hyvaicons->renderHtml('trash', 'w-4'); ?>
                                            </span>
                                        </button>
                                    </div>

                                </div>
                            </div>
                        </template>
                    </div>
                </template>

                <template x-if="itemsCount">
                    <div class="mt-10">
                        <?= $block->getChildHtml('cart-drawer.totals.before'); ?>

                        <div class="flex flex-col w-full justify-center px-3 sm:px-8">
                            <div class="w-full h-16 flex justify-between items-center text-text border-t border-b border-primary mb-6"
                            >
                                <span class="text-sm leading-5"><?= $escaper->escapeHtml(__('Cart Subtotal')) ?> </span>
                                <span x-html="cart.subtotal" class="font-bold"></span>
                            </div>
                            <div class="flex flex-col sm:flex-row justify-between items-center">
                                <a @click.prevent.stop="$dispatch('toggle-authentication',
                                    {url: '<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>'});"
                                    href="<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>"
                                    class="inline-flex btn btn-primary btn-size-lg uppercase visited:text-white sm:order-2 w-[336px]"
                                >
                                    <?= $escaper->escapeHtml(__('Proceed to Checkout')) ?>
                                </a>
                                <a href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart')) ?>"
                                    class="uppercase leading-6 mt-6 sm:mt-0 block text-center"
                                >
                                    <?= $escaper->escapeHtml(__('View and Edit Cart')) ?>
                                </a>
                            </div>
                            <?= $block->getChildHtml('extra_actions') ?>
                        </div>
                    </div>
                </template>

                <?= $block->getChildHtml('cart-drawer.bottom'); ?>
            </div>

            <button
                type="button"
                @click="closeCartDrawer"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Close minicart')) ?>"
                class="absolute top-0 right-0 py-6 px-3 sm:px-7 text-text transition-colors hover:text-black flex items-center"
            >
                Close
                <span aria-hidden="true">
                    <?= $hyvaicons->renderHtml('close-menu', 'w-3 h-3 ml-2'); ?>
                </span>
            </button>
        </div>
        <?= $block->getChildHtml('loading') ?>
    </div>

</section>
